import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useConversationContext } from "./ConversationProvider";
import { SpriteRenderer } from "./SpriteRenderer";
import { Header } from "../layout/Header";
import { AssistantFirstRun } from "./AssistantFirstRun";
import { AssistantChat } from "./AssistantChat";
import { AssistantMemories } from "./AssistantMemories";
import { AssistantJournals } from "./AssistantJournals";
import { AssistantAvatars } from "./AssistantAvatars";
import "./AssistantView.css";

type TabId = "chat" | "memories" | "journals" | "avatar";

const TABS: { id: TabId; label: string }[] = [
  { id: "chat", label: "Chat" },
  { id: "memories", label: "Memories" },
  { id: "journals", label: "Journals" },
  { id: "avatar", label: "Avatar" },
];

export function AssistantView() {
  const navigate = useNavigate();
  const {
    activeAvatar,
    conversationId,
    isLoading,
    pendingCompactionConvId,
    isCompacting,
    compactionError,
    pendingReview,
    consumePendingReview,
    handleFirstRunComplete,
    handleConversationEnding,
    handleConversationStart,
    setTimerViewing,
    handleAvatarSwitch,
    handleAvatarDeleted,
    handleAvatarDataWiped,
    handleCompactNow,
    handleCopyRawData,
    handlePasteResponse,
    onStreamStart,
    onStreamEnd,
    onUserTyping,
    onUserSentMessage,
    expression,
    spriteDataUrl,
    refreshActiveAvatar,
    // Conversation state from hub
    messages,
    isStreaming,
    conversationError,
    currentStreamText,
    isConversationCompacting,
    pendingActions,
    t0Expression,
    cloudAiEnabled,
    historyLoaded,
    sendMessage,
    retry,
    endActiveConversation,
    injectMessage,
    clearPendingActions,
    clearT0Expression,
  } = useConversationContext();

  // Pause timer while on /assistant page
  useEffect(() => {
    setTimerViewing(true);
    return () => setTimerViewing(false);
  }, [setTimerViewing]);

  const [activeTab, setActiveTab] = useState<TabId>("chat");
  const [showPasteModal, setShowPasteModal] = useState(false);
  const [pasteValue, setPasteValue] = useState("");

  // Scale hero name font size based on character count
  const heroNameSize = useMemo(() => {
    const len = activeAvatar?.name?.length ?? 0;
    if (len <= 6) return "1.75rem";
    if (len <= 12) return "1.5rem";
    if (len <= 18) return "1.25rem";
    return "1rem";
  }, [activeAvatar?.name]);

  // Wrap avatar switch to also switch to chat tab locally
  const onAvatarSwitch = useCallback(
    async (avatarId: string) => {
      await handleAvatarSwitch(avatarId);
      setActiveTab("chat");
    },
    [handleAvatarSwitch],
  );

  if (isLoading) {
    return (
      <div className="assistant-view">
        <Header title="Assistant" />
        <div className="assistant-view__body">
          <p style={{ padding: "2rem", color: "var(--color-text-tertiary)" }}>
            Loading...
          </p>
        </div>
      </div>
    );
  }

  if (!activeAvatar) {
    return (
      <div className="assistant-view">
        <Header title="Assistant" />
        <div className="assistant-view__body">
          <AssistantFirstRun onComplete={handleFirstRunComplete} />
        </div>
      </div>
    );
  }

  return (
    <div className="assistant-view">
      <Header title="Assistant" />
      <div className="assistant-view__body">
        <div className="assistant-view__content">
          {/* Compaction retry banner */}
          {pendingCompactionConvId && (
            <div className="assistant-view__recovery-banner assistant-view__recovery-banner--compaction">
              <span className="assistant-view__recovery-text">
                A previous conversation needs to be processed.
              </span>
              {compactionError && (
                <span className="assistant-view__recovery-error">{compactionError}</span>
              )}
              <div className="assistant-view__recovery-actions">
                <button
                  className="assistant-view__recovery-btn assistant-view__recovery-btn--primary"
                  onClick={handleCompactNow}
                  disabled={isCompacting}
                >
                  {isCompacting ? "Processing..." : "Compact Now"}
                </button>
                <button
                  className="assistant-view__recovery-btn"
                  onClick={handleCopyRawData}
                  title="Copy the full compaction request to clipboard for use with an external AI"
                >
                  Copy Raw Data
                </button>
                <button
                  className="assistant-view__recovery-btn"
                  onClick={() => setShowPasteModal(true)}
                  title="Paste a compaction response generated by an external AI (advanced)"
                >
                  Paste Response
                </button>
              </div>
            </div>
          )}

          <div className="assistant-view__tabs">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                className={`assistant-view__tab ${activeTab === tab.id ? "assistant-view__tab--active" : ""}`}
                onClick={() => setActiveTab(tab.id)}
              >
                {tab.label}
              </button>
            ))}
          </div>
          <div className="assistant-view__tab-content">
            {activeTab === "chat" && (
              <>
                <div className="assistant-view__chat-hero">
                  <SpriteRenderer
                    spriteDataUrl={spriteDataUrl}
                    expression={expression}
                    size={160}
                    fallbackText={activeAvatar.name}
                  />
                  <span
                    className="assistant-view__chat-hero-name"
                    style={{ "--hero-name-size": heroNameSize } as React.CSSProperties}
                  >
                    {activeAvatar.name}
                  </span>
                </div>
                <AssistantChat
                  conversationId={conversationId}
                  messages={messages}
                  isStreaming={isStreaming}
                  error={conversationError}
                  currentStreamText={currentStreamText}
                  isCompacting={isConversationCompacting}
                  pendingActions={pendingActions}
                  t0Expression={t0Expression}
                  cloudAiEnabled={cloudAiEnabled}
                  historyLoaded={historyLoaded}
                  sendMessage={sendMessage}
                  retry={retry}
                  endConversation={endActiveConversation}
                  injectMessage={injectMessage}
                  clearPendingActions={clearPendingActions}
                  clearT0Expression={clearT0Expression}
                  onConversationStart={handleConversationStart}
                  onConversationEnding={handleConversationEnding}
                  pendingReview={pendingReview}
                  onPendingReviewConsumed={consumePendingReview}
                  navigate={navigate}
                  onExpressionStreamStart={onStreamStart}
                  onExpressionStreamEnd={onStreamEnd}
                  onExpressionUserTyping={onUserTyping}
                  onExpressionUserSentMessage={onUserSentMessage}
                  avatarName={activeAvatar.name}
                />
              </>
            )}
            {activeTab === "memories" && <AssistantMemories avatarId={activeAvatar.id} />}
            {activeTab === "journals" && <AssistantJournals avatarId={activeAvatar.id} />}
            {activeTab === "avatar" && (
              <AssistantAvatars
                activeAvatarId={activeAvatar.id}
                isStreaming={isStreaming}
                onAvatarSwitch={onAvatarSwitch}
                onAvatarDeleted={handleAvatarDeleted}
                onAvatarDataWiped={handleAvatarDataWiped}
                onSpriteChanged={refreshActiveAvatar}
              />
            )}
          </div>
        </div>
      </div>

      {/* Paste Response Modal */}
      {showPasteModal && (
        <div
          className="assistant-view__paste-modal-backdrop"
          onClick={() => setShowPasteModal(false)}
        >
          <div
            className="assistant-view__paste-modal"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="assistant-view__paste-modal-title">
              Paste Compaction Response
            </h3>
            <p className="assistant-view__paste-modal-desc">
              Paste the JSON response from an external AI. It must have this structure:
            </p>
            <pre className="assistant-view__paste-modal-example">
              {`{
  "summary": "...",
  "memories": [
    { "content": "...", "importance": 1-10, "category": "preference|opinion|fact|general" }
  ],
  "supersededMemories": ["memory-id-1", ...]
}`}
            </pre>
            <textarea
              className="assistant-view__paste-modal-textarea"
              value={pasteValue}
              onChange={(e) => setPasteValue(e.target.value)}
              placeholder="Paste JSON here..."
              rows={10}
            />
            {compactionError && (
              <div className="assistant-view__paste-modal-error">{compactionError}</div>
            )}
            <div className="assistant-view__paste-modal-actions">
              <button
                className="assistant-view__recovery-btn assistant-view__recovery-btn--primary"
                onClick={() => handlePasteResponse(pasteValue)}
                disabled={isCompacting || !pasteValue.trim()}
              >
                {isCompacting ? "Processing..." : "Apply"}
              </button>
              <button
                className="assistant-view__recovery-btn"
                onClick={() => {
                  setShowPasteModal(false);
                  setPasteValue("");
                }}
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
