/**
 * Tag taxonomy — maps SteamSpy community tags into display categories.
 *
 * Tags not listed here are placed in the "Other" category automatically.
 * Case-insensitive lookup is used at runtime so the casing here is for readability only.
 */

export type TagCategory =
  | "Genre"
  | "Play Style"
  | "Theme / Setting"
  | "Mood / Aesthetic"
  | "Mechanics"
  | "Perspective"
  | "Content"
  | "Platform / Access"
  | "Meta"
  | "Miscellaneous"
  | "Other";

/** Display order for categories in the filter UI. */
export const TAG_CATEGORY_ORDER: TagCategory[] = [
  "Genre",
  "Play Style",
  "Theme / Setting",
  "Mood / Aesthetic",
  "Mechanics",
  "Perspective",
  "Content",
  "Platform / Access",
  "Meta",
  "Miscellaneous",
  "Other",
];

/**
 * Static mapping: tag name → category.
 * All keys are lowercase for case-insensitive matching.
 */
const TAXONOMY: Record<string, TagCategory> = {
  // ── Genre ────────────────────────────────────────────────────────
  action: "Genre",
  adventure: "Genre",
  rpg: "Genre",
  strategy: "Genre",
  simulation: "Genre",
  puzzle: "Genre",
  platformer: "Genre",
  racing: "Genre",
  sports: "Genre",
  fighting: "Genre",
  shooter: "Genre",
  fps: "Genre",
  rts: "Genre",
  mmorpg: "Genre",
  jrpg: "Genre",
  crpg: "Genre",
  "action rpg": "Genre",
  "action-adventure": "Genre",
  "action roguelike": "Genre",
  "dungeon crawler": "Genre",
  "hack and slash": "Genre",
  metroidvania: "Genre",
  "puzzle-platformer": "Genre",
  "souls-like": "Genre",
  "turn-based strategy": "Genre",
  "turn-based combat": "Genre",
  "turn-based tactics": "Genre",
  "turn-based": "Genre",
  "grand strategy": "Genre",
  "real-time with pause": "Genre",
  "real time tactics": "Genre",
  "tactical rpg": "Genre",
  "strategy rpg": "Genre",
  "tower defense": "Genre",
  "bullet hell": "Genre",
  "shoot 'em up": "Genre",
  "side scroller": "Genre",
  "2d platformer": "Genre",
  "3d platformer": "Genre",
  "card game": "Genre",
  "card battler": "Genre",
  deckbuilding: "Genre",
  "roguelike deckbuilder": "Genre",
  "board game": "Genre",
  "word game": "Genre",
  "match 3": "Genre",
  "auto battler": "Genre",
  "battle royale": "Genre",
  "walking simulator": "Genre",
  "visual novel": "Genre",
  "dating sim": "Genre",
  "hidden object": "Genre",
  "point & click": "Genre",
  "interactive fiction": "Genre",
  "choose your own adventure": "Genre",
  "immersive sim": "Genre",
  "colony sim": "Genre",
  "city builder": "Genre",
  "farming sim": "Genre",
  "life sim": "Genre",
  "automobile sim": "Genre",
  "space sim": "Genre",
  "job simulator": "Genre",
  "god game": "Genre",
  "political sim": "Genre",
  "looter shooter": "Genre",
  "hero shooter": "Genre",
  "third-person shooter": "Genre",
  "extraction shooter": "Genre",
  "beat 'em up": "Genre",
  "creature collector": "Genre",
  "social deduction": "Genre",
  moba: "Genre",
  "rogue-like": "Genre",
  "rogue-lite": "Genre",
  "twin stick shooter": "Genre",
  "top-down shooter": "Genre",
  "arena shooter": "Genre",
  "precision platformer": "Genre",
  "2d fighter": "Genre",
  "3d fighter": "Genre",
  "party-based rpg": "Genre",
  "character action game": "Genre",
  "action rts": "Genre",
  solitaire: "Genre",
  pinball: "Genre",

  // ── Play Style ───────────────────────────────────────────────────
  singleplayer: "Play Style",
  multiplayer: "Play Style",
  "co-op": "Play Style",
  "online co-op": "Play Style",
  "local co-op": "Play Style",
  "local multiplayer": "Play Style",
  "split screen": "Play Style",
  pvp: "Play Style",
  pve: "Play Style",
  "massively multiplayer": "Play Style",
  "4 player local": "Play Style",
  "party game": "Play Style",
  competitive: "Play Style",
  "asynchronous multiplayer": "Play Style",
  "team-based": "Play Style",
  "co-op campaign": "Play Style",
  "e-sports": "Play Style",

  // ── Theme / Setting ──────────────────────────────────────────────
  "sci-fi": "Theme / Setting",
  fantasy: "Theme / Setting",
  "dark fantasy": "Theme / Setting",
  horror: "Theme / Setting",
  "survival horror": "Theme / Setting",
  "psychological horror": "Theme / Setting",
  "post-apocalyptic": "Theme / Setting",
  medieval: "Theme / Setting",
  historical: "Theme / Setting",
  cyberpunk: "Theme / Setting",
  steampunk: "Theme / Setting",
  space: "Theme / Setting",
  underwater: "Theme / Setting",
  "alternate history": "Theme / Setting",
  "world war ii": "Theme / Setting",
  "cold war": "Theme / Setting",
  dystopian: "Theme / Setting",
  "dystopian ": "Theme / Setting", // trailing space variant from Steam
  futuristic: "Theme / Setting",
  mythology: "Theme / Setting",
  western: "Theme / Setting",
  america: "Theme / Setting",
  rome: "Theme / Setting",
  gothic: "Theme / Setting",
  lovecraftian: "Theme / Setting",
  noir: "Theme / Setting",
  military: "Theme / Setting",
  war: "Theme / Setting",
  crime: "Theme / Setting",
  heist: "Theme / Setting",
  pirates: "Theme / Setting",
  supernatural: "Theme / Setting",
  vampire: "Theme / Setting",
  werewolves: "Theme / Setting",
  zombies: "Theme / Setting",
  aliens: "Theme / Setting",
  dinosaurs: "Theme / Setting",
  dragons: "Theme / Setting",
  demons: "Theme / Setting",
  robots: "Theme / Setting",
  mechs: "Theme / Setting",
  cats: "Theme / Setting",
  dog: "Theme / Setting",
  elf: "Theme / Setting",
  dwarf: "Theme / Setting",
  mars: "Theme / Setting",
  superhero: "Theme / Setting",
  transhumanism: "Theme / Setting",

  // ── Mood / Aesthetic ─────────────────────────────────────────────
  atmospheric: "Mood / Aesthetic",
  funny: "Mood / Aesthetic",
  relaxing: "Mood / Aesthetic",
  colorful: "Mood / Aesthetic",
  cute: "Mood / Aesthetic",
  casual: "Mood / Aesthetic",
  difficult: "Mood / Aesthetic",
  dark: "Mood / Aesthetic",
  "dark humor": "Mood / Aesthetic",
  "dark comedy": "Mood / Aesthetic",
  comedy: "Mood / Aesthetic",
  satire: "Mood / Aesthetic",
  "parody ": "Mood / Aesthetic", // trailing space variant from Steam
  parody: "Mood / Aesthetic",
  wholesome: "Mood / Aesthetic",
  cozy: "Mood / Aesthetic",
  beautiful: "Mood / Aesthetic",
  emotional: "Mood / Aesthetic",
  surreal: "Mood / Aesthetic",
  psychedelic: "Mood / Aesthetic",
  minimalist: "Mood / Aesthetic",
  stylized: "Mood / Aesthetic",
  retro: "Mood / Aesthetic",
  classic: "Mood / Aesthetic",
  nostalgia: "Mood / Aesthetic",
  "old school": "Mood / Aesthetic",
  epic: "Mood / Aesthetic",
  cinematic: "Mood / Aesthetic",
  immersive: "Mood / Aesthetic",
  violent: "Mood / Aesthetic",
  gore: "Mood / Aesthetic",
  blood: "Mood / Aesthetic",
  mature: "Mood / Aesthetic",
  memes: "Mood / Aesthetic",
  addictive: "Mood / Aesthetic",
  ambient: "Mood / Aesthetic",

  // ── Mechanics / Systems ──────────────────────────────────────────
  "open world": "Mechanics",
  sandbox: "Mechanics",
  crafting: "Mechanics",
  survival: "Mechanics",
  building: "Mechanics",
  "base-building": "Mechanics",
  management: "Mechanics",
  "resource management": "Mechanics",
  economy: "Mechanics",
  capitalism: "Mechanics",
  exploration: "Mechanics",
  stealth: "Mechanics",
  physics: "Mechanics",
  "procedural generation": "Mechanics",
  "character customization": "Mechanics",
  "choices matter": "Mechanics",
  "multiple endings": "Mechanics",
  moddable: "Mechanics",
  "replay value": "Mechanics",
  idler: "Mechanics",
  clicker: "Mechanics",
  automation: "Mechanics",
  trading: "Mechanics",
  "level editor": "Mechanics",
  "inventory management": "Mechanics",
  "perma death": "Mechanics",
  destruction: "Mechanics",
  parkour: "Mechanics",
  "time management": "Mechanics",
  "time manipulation": "Mechanics",
  "time travel": "Mechanics",
  cooking: "Mechanics",
  fishing: "Mechanics",
  hunting: "Mechanics",
  farming: "Mechanics",
  mining: "Mechanics",
  agriculture: "Mechanics",
  hacking: "Mechanics",
  programming: "Mechanics",
  typing: "Mechanics",
  conversation: "Mechanics",
  "dynamic narration": "Mechanics",
  narration: "Mechanics",
  nonlinear: "Mechanics",
  loot: "Mechanics",
  "lore-rich": "Mechanics",
  combat: "Mechanics",
  swordplay: "Mechanics",
  archery: "Mechanics",
  magic: "Mechanics",
  investigation: "Mechanics",
  "score attack": "Mechanics",
  collectathon: "Mechanics",
  "quick-time events": "Mechanics",
  "bullet time": "Mechanics",
  "open world survival craft": "Mechanics",
  diplomacy: "Mechanics",
  "escape room": "Mechanics",
  gambling: "Mechanics",
  "martial arts": "Mechanics",

  // ── Perspective / Presentation ───────────────────────────────────
  "first-person": "Perspective",
  "third person": "Perspective",
  "top-down": "Perspective",
  isometric: "Perspective",
  "2d": "Perspective",
  "3d": "Perspective",
  "pixel graphics": "Perspective",
  "hand-drawn": "Perspective",
  cartoon: "Perspective",
  cartoony: "Perspective",
  anime: "Perspective",
  "comic book": "Perspective",
  voxel: "Perspective",
  "2.5d": "Perspective",
  "text-based": "Perspective",
  fmv: "Perspective",
  "3d vision": "Perspective",

  // ── Content Descriptors ──────────────────────────────────────────
  "sexual content": "Content",
  nudity: "Content",
  hentai: "Content",
  nsfw: "Content",
  "lgbtq+": "Content",
  romance: "Content",
  thriller: "Content",
  drama: "Content",
  mystery: "Content",
  "family friendly": "Content",
  psychological: "Content",

  // ── Platform / Access ────────────────────────────────────────────
  "free to play": "Platform / Access",
  "early access": "Platform / Access",
  vr: "Platform / Access",
  controller: "Platform / Access",
  "touch-friendly": "Platform / Access",
  "mouse only": "Platform / Access",
  "asymmetric vr": "Platform / Access",

  // ── Meta / Non-Game ──────────────────────────────────────────────
  software: "Meta",
  utilities: "Meta",
  soundtrack: "Meta",
  education: "Meta",
  "design & illustration": "Meta",
  "game development": "Meta",
  kickstarter: "Meta",
  crowdfunded: "Meta",
  benchmark: "Meta",
  tutorial: "Meta",
  mod: "Meta",
  sequel: "Meta",
  remake: "Meta",
  lego: "Meta",
  "games workshop": "Meta",
  "dungeons & dragons": "Meta",
  rpgmaker: "Meta",
  gamemaker: "Meta",
  "web publishing": "Meta",
  "audio production": "Meta",
  "video production": "Meta",
  "photo editing": "Meta",
  "animation & modeling": "Meta",
  "software training": "Meta",
  hardware: "Meta",
  "360 video": "Meta",

  // ── Miscellaneous ────────────────────────────────────────────────
  "story rich": "Miscellaneous",
  "great soundtrack": "Miscellaneous",
  driving: "Miscellaneous",
  flight: "Miscellaneous",
  trains: "Miscellaneous",
  transportation: "Miscellaneous",
  sailing: "Miscellaneous",
  naval: "Miscellaneous",
  nature: "Miscellaneous",
  illuminati: "Miscellaneous",
  "female protagonist": "Miscellaneous",
  "villain protagonist": "Miscellaneous",
  "silent protagonist": "Miscellaneous",
  tabletop: "Miscellaneous",
  "hex grid": "Miscellaneous",
  wargame: "Miscellaneous",
  music: "Miscellaneous",
  rhythm: "Miscellaneous",
  runner: "Miscellaneous",
  assassin: "Miscellaneous",
  "class-based": "Miscellaneous",
  "fast-paced": "Miscellaneous",
  linear: "Miscellaneous",
  short: "Miscellaneous",
  "4x": "Miscellaneous",
  abstract: "Miscellaneous",
  logic: "Miscellaneous",
  dice: "Miscellaneous",
  political: "Miscellaneous",
  politics: "Miscellaneous",
  science: "Miscellaneous",
  philosophical: "Miscellaneous",
  minigames: "Miscellaneous",
  trivia: "Miscellaneous",
  "shop keeper": "Miscellaneous",
  snow: "Miscellaneous",
  indie: "Miscellaneous",
  horses: "Miscellaneous",
  offroad: "Miscellaneous",
  golf: "Miscellaneous",
  "mini golf": "Miscellaneous",
  bowling: "Miscellaneous",
  skiing: "Miscellaneous",
  "football (soccer)": "Miscellaneous",
  "football (american)": "Miscellaneous",
  chess: "Miscellaneous",
  detective: "Miscellaneous",
  submarine: "Miscellaneous",
  "vehicular combat": "Miscellaneous",
  tanks: "Miscellaneous",
  "real-time": "Miscellaneous",
  "hobby sim": "Miscellaneous",
  "medical sim": "Miscellaneous",
  "cult classic": "Miscellaneous",
  "based on a novel": "Miscellaneous",
  gaming: "Miscellaneous",
  "warhammer 40k": "Miscellaneous",
  "1980s": "Miscellaneous",
  "1990's": "Miscellaneous",
};

/** Look up the category for a tag name (case-insensitive). */
export function getTagCategory(tagName: string): TagCategory {
  return TAXONOMY[tagName.toLowerCase().trim()] ?? "Other";
}

/**
 * Group a list of tags by their taxonomy category.
 * Returns entries in TAG_CATEGORY_ORDER, omitting empty groups.
 */
export function groupTagsByCategory<T extends { name: string }>(
  tags: T[],
): { category: TagCategory; tags: T[] }[] {
  const groups = new Map<TagCategory, T[]>();
  for (const tag of tags) {
    const cat = getTagCategory(tag.name);
    const list = groups.get(cat);
    if (list) {
      list.push(tag);
    } else {
      groups.set(cat, [tag]);
    }
  }

  return TAG_CATEGORY_ORDER.filter((cat) => groups.has(cat)).map((cat) => ({
    category: cat,
    tags: groups.get(cat)!,
  }));
}
